platform :ios, '8.0'

target 'RNHotels_Example' do
  pod 'RNHotels', path: '../../../..'

  pod 'React', :podspec => 'Local Pods/React.podspec.json'
  pod 'yoga',  :podspec => 'Local Pods/yoga.podspec.json'
    
  pod 'RNLogging', :git => 'git@gitlab.skypicker.com:mobile/react-native-native-modules.git'
  pod 'RNTranslationManager', :git => 'git@gitlab.skypicker.com:mobile/react-native-native-modules.git'
  pod 'RNColors', :git => 'git@gitlab.skypicker.com:mobile/react-native-native-modules.git'
  pod 'RNCurrencyManager', :git => 'git@gitlab.skypicker.com:mobile/react-native-native-modules.git'
  pod 'RNDeviceInfo', :git => 'git@gitlab.skypicker.com:mobile/react-native-native-modules.git'

  pod 'react-native-maps', :git => 'https://github.com/react-community/react-native-maps.git', :tag => 'v0.21.0'
  pod 'RNVectorIcons', :git => 'https://github.com/oblador/react-native-vector-icons', :tag => 'v4.6.0'
end
